# Generated by Django 4.2.2 on 2023-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_rssidataless_rssidatamore_delete_rssidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssidataless',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rssidatamore',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
