# Generated by Django 4.2.2 on 2023-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_alter_rssidataless_id_alter_rssidatamore_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
