# Generated by Django 4.2.1 on 2023-06-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_periodictask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodicTask',
        ),
    ]
